### ISSUE TITLE
Missing support for text translation

### ISSUE THREAD

**Issue by Xenap** [EverMCServer/vscode-BetonQuest#1]
BetonQuest documentation: https://docs.betonquest.org/2.0-DEV/Documentation/Features/Conversations/#translations

**Comment by k-jiang** [comment]
It's working in progress. Might takes some times to finish.

**Comment by Xenap** [comment]
Very nice.
I was trying to understand and fiddle around the code to display the languages manually.
But i clearly don't have the level in Typescript yet to contribute.
