### ISSUE TITLE
期待集成插件支持

### ISSUE THREAD

**Issue by zoe-may** [EverMCServer/vscode-BetonQuest#13]
现在对于集成插件的适配看起来还没有起步，可以先把几个常用的插件适配了嘛，比如Citizens2（急需！），感谢大大，这个插件真的太方便了

**Comment by k-jiang** [comment]
谢谢支持！

你是指Citizens2的`Condition`、`Event`、`Objective`吗？我一会儿应该可以加一部分上去。

**Comment by k-jiang** [comment]
v0.5.3 pre-released with Citizens supports.
带 Citizens 支持的 v0.5.3 预发布版上线了。

**Comment by zoe-may** [comment]
> v0.5.3 pre-released with Citizens supports. 带 Citizens 支持的 v0.5.3 预发布版上线了。

感谢大大的付出！！！
