### ISSUE TITLE
[Suggestion] Default lang selection

### ISSUE THREAD

**Issue by Yriokiri** [EverMCServer/vscode-BetonQuest#9]
as the title say, possibility to decide wich language is the default one that the editor use in dialogues creation

**Comment by k-jiang** [comment]
1. Press `Ctrl + Shift + P` (`Cmd + Shift + P` for Mac)
2. Enter `>Preferences: Open Settings (UI)`
3. Search for "BetonQuest"

Then you will find the default  translation setting:

<img width="710" alt="image" src="https://github.com/EverMCServer/vscode-BetonQuest/assets/6910542/a8a45537-b4b5-49c3-9ebb-70dfc92044a1">
